/*
  ==============================================================================
  Table Name: Dim_Calendar
  Description: Dynamic Date Dimension table aligned with ER admission dates.
  ==============================================================================
*/

Dim_Calendar = 
VAR MinDate = DATEVALUE( MIN('Hospital ER Data'[Patient Admission Date]) )
VAR MaxDate = DATEVALUE( MAX('Hospital ER Data'[Patient Admission Date]) )
RETURN
ADDCOLUMNS (
    CALENDAR ( MinDate, MaxDate ),
    "Year", YEAR ( [Date] ),
    "Month Name", FORMAT ( [Date], "MMMM" ),
    "Month Number", MONTH ( [Date] ),
    "Year Month", FORMAT ( [Date], "YYYY MMM" ),
    "Year Month Sort", YEAR ( [Date] ) * 100 + MONTH ( [Date] ),
    "Quarter", "Q" & FORMAT ( [Date], "Q" ),
    "Day of Week", FORMAT ( [Date], "dddd" ),
    "Day of Week Sort", WEEKDAY ( [Date], 2 ), -- 1 = Monday, 7 = Sunday
    "Day Assessment", WEEKDAY ( [Date] )
)
